// Generated by CoffeeScript 1.3.1
(function() {
  var _;

  _ = function($) {
    return $.fn.resizable = function(options) {
      var $div, settings;
      settings = $.extend({
        duration: 250,
        callback: function() {}
      }, options);
      $div = $(this).filter('div').each(function() {
        var $editable, $element, resize;
        $element = $(this).css({
          resize: 'none',
          'overflow-y': 'hidden'
        });
        if (!$element.children('[data-resizable-inner="1"]').length) {
          $element.html($('<div>').attr({
            'data-resizable-inner': 1,
            'contenteditable': 'true'
          }).css({
            width: $element.width(),
            height: 'auto',
            'min-height': $element.height()
          }).html($element.html()));
        }
        $editable = $($element.find('[data-resizable-inner="1"]')[0]);
        resize = function() {
          $element.animate({
            height: $editable.height()
          }, settings.duration).promise().then(settings.callback);
        };
        $editable.unbind('.resizable').bind('change.resizable', resize).bind('keyup.resizable', resize);
        return $element;
      });
      return this;
    };
  };

  _(jQuery);

}).call(this);
